# -*- coding: utf-8 -*-
"""Copia de Python_MySQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDaU3rf4nblLmR2RIyqtkw0MnGV_tLoP
"""

!pip install mysql-connector-python

import mysql.connector

# Establish a connection to the database
def create_connection():
    connection = mysql.connector.connect(
        host="",
        user="admin",
        password="Admin123",
        database="yt_demo"
    )
    return connection

connection = create_connection()
connection

# Create a sample table
def create_table(connection):
    cursor = connection.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS sample (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), age INT)")

create_table(connection)

# Insert a record
def insert_record(connection, name, age):
    cursor = connection.cursor()
    query = "INSERT INTO sample (name, age) VALUES (%s, %s)"
    cursor.execute(query, (name, age))
    connection.commit()

insert_record(connection, "John Doe", 30)
insert_record(connection, "Jane Smith", 28)

# Select records
def select_records(connection):
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM sample")
    rows = cursor.fetchall()
    for row in rows:
        print(row)

select_records(connection)

# Update a record
def update_record(connection, name, age, id):
    cursor = connection.cursor()
    query = "UPDATE sample SET name = %s, age = %s WHERE id = %s"
    cursor.execute(query, (name, age, id))
    connection.commit()

update_record(connection, "John Doe", 31, 1)
select_records(connection)

# Delete a record
def delete_record(connection, id):
    cursor = connection.cursor()
    query = "DELETE FROM sample WHERE id = %s"
    cursor.execute(query, (id,))
    connection.commit()
delete_record(connection, 1)

select_records(connection)

# ...

# Insert multiple records
def insert_multiple_records(connection, records):
    cursor = connection.cursor()
    query = "INSERT INTO sample (name, age) VALUES (%s, %s)"
    cursor.executemany(query, records)
    connection.commit()

# Main function to perform all operations


records = [("John1 Doe", 30), ("Jane1 Smith", 28), ("Alice Brown", 24)]
insert_multiple_records(connection, records)

select_records(connection)